### ISSUE TITLE
setup for python < 3.5 is broken in release 5.0.0

### ISSUE THREAD

**Issue by Amli** [micheles/decorator#99]
Hi,

the current setup let python 2.7 install the 5.0.0 release which is incompatible with anything below 3.5.
A small fix in the setup.py is necessary but this will also require a new release I guess.

**Comment by ca-simone-chiorazzo** [comment]
I would add also that the setup.cfg specify an universal build.

Now that the support for python2 has gone, this is no more true and should be avoided.

**Comment by micheles** [comment]
This is solved, release 5.0.0 has been yanked and replaced by 5.0.1

**Comment by ahnitz** [comment]
@micheles This still appears to be broken to me with 5.0.1. I do the following. 

```
virtualenv -p python2.7 env
source env/bin/activate
pip install setuptools pip --upgrade
pip install decorator
```

I get the following

```
Collecting decorator
  Downloading decorator-5.0.1-py2.py3-none-any.whl (8.6 kB)
ERROR: Package 'decorator' requires a different Python: 2.7.18 not in '>=3.5'
```

This should not have occurred as pip is supposed to pull the last compatible version in this case. I think what may be happening is related to the 'universal' wheel that was produced. It might be that this is short-circuiting the pip logic when selecting a package.
